### ISSUE TITLE
Python Integration

### ISSUE THREAD

**Issue by garrettdowd** [lightpohl/podcast-dl#7]
Hey its me again. I have been trying to build a basic webgui for podcast-dl (like youtube-dl-server) inside of a docker container using a Python webserver framework. I am having a lot of trouble being able to call podcast-dl as a shell command from Python, e.g. `podcast-dl --url XXX`. Running shell commands in Python is not a great way to go about it anyway...

I googled around a bit and could not find any alternative methods. Do you have any thoughts on better ways to integrate podcast-dl into a Python script?

**Comment by lightpohl** [comment]
Hey! Sorry for the delay.

I don't currently have any plans to add an external API because it would add quite a bit of complexity to the tool. Trying to keep it as simple as possible at the moment. If I do rework the code to be more acceptable as a public API, it would be a Node API to match the source.

Running shell commands in Python definitely isn't the most optimal solution, but if I can return better error/response codes from the CLI to make it easier just let me know. 👍
